### ISSUE TITLE
We have issues

### ISSUE THREAD

**Issue by nachtkalmar** [Spatial-Systems-Biology-Freiburg/2022-SS-Intro-Sys-Bio#1]
Hi @jonaspleyer!
Ex.7 hier haben wir jetzt lhs benutzt um M = 10**6 parameter Kombinationen zu generieren mit boundary wie gegeben. also Listen mit jeweils 12 "verschiedenen", also random, Zahlen zwischen 0,05 und 50. Was willst du uns mit formel 3 ( pi = 10 ** qi) sagen? Müssen wir aus diesen Zahlen jetzt noch den log nehmen, um dann an das qi zu kommen, das uns wirklich interessiert? Oder andersrum? Wir sind verwirrt- das ist ja nichts neues. 

Ex.8
"use provided function to filter parameters" - wo ist die?

Grüße vom Dream Team

**Comment by jonaspleyer** [comment]
Bitte lest den Wikipedia Artikel zu Latin-Hypercube Sampling. Das ist nicht das gleiche, wie Random-Sampling (dafür waren ja die Verlinkungen der Referenzen gedacht).
https://en.wikipedia.org/wiki/Latin_hypercube_sampling

Es gibt libraries wie scipy, die bereits LHS implementieren:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.qmc.LatinHypercube.html

Latin-Hypercube sampelt einen hypercube gleichmäßig ab. Das gibt euch dann die punkte q_i. Allerdings wolle wir diese Punkte noch transformieren. Wie ihr bereits richtig an der Aufgabe gelesen habt, muss dafür die Gleichung, die ich euch gegeben habe verwenden (formel 3).
Allerdings soll in dieser Transformation die Bedingung 0.05<p_i<50.0 gelten. Was bedeutet das für die Parameter q_i ?

**Comment by jonaspleyer** [comment]
Die "provided funtions" bekommt ihr, wenn ich sehe, dass das parameter sampling mit LHS klappt.
Man sollte theoretisch das Sampling auch ohne diese Filter-Funktion schon durchlaufen lassen können und die Filter dann am Ende einfach zwischen parameter sampling und simulation laufen lassen dazwischenschalten.

Da die simulation von 10^6 parameter-sets durchaus einiges an Zeit in anspruch nehmen kann, solltet ihr die Ergebnisse davon in geeigneter Art und Weise als datei oder anderweitig speichern. Außerdem könnte man sich überlegen, diese sofort nach Beendigung von jeder individuellen simulation und nicht erst nach Abschluss aller simulationen zu sichern, um einen Absturz oder andere Fehler im Programm vorzubeugen.

**Comment by nachtkalmar** [comment]
Hallo Jonas,
wir haben uns gestern mehrere Stunden getroffen und in der Tat den Wikipedia Artikel durchgelesen und sogar Literatur darüber hinaus -.- Wir waren auch von alleine schlau genug, zu googlen ob es Implementierungen gibt, die wir verwenden können. Wir haben mehrere Verglichen und uns [hierfür ](https://smt.readthedocs.io/en/latest/_src_docs/sampling_methods/lhs.html#id3) entschieden, da wir hier bereits die Grenzen mitgeben können, was in der scipy Implementierung nicht der Fall ist.
Wir haben wie bereits erwähnt Code der durchläuft, ich hänge ihn an zu deiner Begutachtung, ob das so passt.
Grüße
[lhs_trials.zip](https://github.com/Spatial-Systems-Biology-Freiburg/2022-SS-Intro-Sys-Bio/files/9076135/lhs_trials.zip)

**Comment by jonaspleyer** [comment]
schaut euch nochmal genau an, was q_i und was p_i ist. Es wurden grenzen für p_i vorgegeben, aber ihr habt Grenzen für q_i angesetzt.
Außérdem: python kann folgendes:
```
>>> a = ["a", "b"]
>>> [a] * 5
[['a', 'b'], ['a', 'b'], ['a', 'b'], ['a', 'b'], ['a', 'b']]
```

**Comment by jonaspleyer** [comment]
Noch ein paar weitere Anmerkungen:
1. Das weitere Vorgehen ist auch ohne die "provided functions" möglich. Also Parameter Sampling ==> System für alle parameter lösen ==> Ergebnisse auf Musterbildung untersuchen
2. Ihr solltet nicht nur ein minimal working example schicken. Der Code, den ihr geschrieben habt, interagiert in keiner Art und Weise mit bereits Bestehendem. Dann aber bitte natürlich auch alles mitschicken, was man braucht, um den Code laufen lassen zu können. Also vor Allem Dateien/Skripte, die ihr bereits verändert habt.
3. Allgemein gibt es viele Dinge, die in parallel gemacht werden können: Vortrag vorbereiten, Code für Parameter-Sampling,  Code und Vorgehen für Ergebnis-Analyse
